#!/bin/sh

mkdir -p /mnt/overlay/etc/

# Network
mkdir -p /mnt/overlay/etc/NetworkManager/system-connections

if [ ! -f /mnt/overlay/etc/hostname ]; then
    cp -fp /etc/hostname /mnt/overlay/etc/hostname
fi

if [ ! -d /mnt/overlay/home/haos ]; then
    mkdir -p /mnt/overlay/home/haos
    chown -R haos:haos /mnt/overlay/home/haos
    cp -r /home/haos/.* /mnt/overlay/home/haos/
fi

if [ ! -f /mnt/overlay/etc/hosts ]; then
    cp -fp /etc/hosts /mnt/overlay/etc/hosts
fi

# TimeSync
if [ ! -f /mnt/overlay/etc/systemd/timesyncd.conf ]; then
    mkdir -p /mnt/overlay/etc/systemd
    cp -fp /etc/systemd/timesyncd.conf /mnt/overlay/etc/systemd/timesyncd.conf
fi
