name: Build and Release Firmware

on:
  push:
    branches: ["push"]
  workflow_dispatch:  # 支持手动触发

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0
          submodules: true
    - name: Install  dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y mmdebstrap libconfuse-dev qemu-user-static make gcc rauc u-boot-tools mtools erofs-utils
        pip install pyelftools
    - name: build rootfs
      run: scripts/mk-ubuntu.sh


    - name: Upload homeassistant.img
      uses: actions/upload-artifact@v4
      with:
        name: homeassistant.img.zip
        path: |
          homeassistant.img
  
    - name: Upload rootfs
      uses: actions/upload-artifact@v4
      with:
        name: rootfs.zip
        path: |
          rootfs.tar.gz

        retention-days: 30          # 自定义保留天数[7](@ref)
