name: Build and Release Firmware

on:
  push:
    tags: ["v*"]  # 仅当推送v开头的标签时触发（如v1.0.0）
  workflow_dispatch:  # 支持手动触发

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0
          submodules: true

    - name: build rootfs
      run: make clean;make rk3399-custom


    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-outputs
        path: |
          *.img

        retention-days: 7          # 自定义保留天数[7](@ref)
